
name: publish

on:
  push:
    branches: [main, dev]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # src: https://colinsalmcorner.com/github-composite-actions/
      # (optional) enable experimental features for --squash command. if you don't use --squash then remove this step and the --squash tag in build and publish step
      - name: Enable experimental features for the Docker daemon and CLI
        run: |
          echo $'{\n "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker version -f '{{.Server.Experimental}}'

      - name: GHCR Login
        uses: docker/login-action@v1 #https://github.com/docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and publish
        run: | # change 'smart-cam' to whatever you want to name the image and 'latest' to whatever tag you want. existing images will be overwritten
          docker build . --squash --tag ghcr.io/${{ github.repository }}/smart-cam:latest 
          docker run ghcr.io/${{ github.repository }}/smart-cam:latest
          docker push ghcr.io/${{ github.repository }}/smart-cam:latest